version: '3'

services:
  web:
    container_name: shk-pilot-web
    build:
      context: ./web
      dockerfile: ./dockerfile
    ports:
      - "4200:4200"
    networks: 
      - shk-net
    volumes: 
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    env_file:
     - ./ops/localhost.env

  api:
    container_name: shk-pilot-api
    build:
      context: ./api
      dockerfile: dockerfile
    environment: 
      - EXAMPLE_1=shk-pilot
      - EXAMPLE_2=shk-pilot
      - EXAMPLE_3=shk-pilot
    ports:
      - "3001:3001"
    networks: 
      - shk-net
    volumes: 
      - ./api:/shk/dev/api
    #  - /mep/dev/api/node_modules

  api_db:
    container_name: shk-pilot-db
    build:
      context: ./
      dockerfile: ./db/dockerfile
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql1
    networks: 
      - shk-net

  # api-db:
  #   container_name: shk-pilot-db
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: dev-pass
  #     MYSQL_DATABASE: shk-pilot
  #   ports:
  #     - "3306:3306"
  #   networks: 
  #     - shk-net
  #   volumes:
  #     - ./.api-db:/var/lib/mysql

volumes:
  dbdata:

networks: 
  shk-net:
    driver: bridge