FROM        node:10

ENV         NPM_CONFIG_LOGLEVEL warn

RUN         npm install -g nodemon

RUN         mkdir -p /shk/dev/api
RUN         mkdir -p /shk/dev/shared

WORKDIR     /shk/dev/api

EXPOSE      3001

RUN mkdir -p /shk/dev/api/node_modules && chown -R node:node /shk/dev/api

CMD [ "tail", "-F", "anything"]
