FROM node:11

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN apt-get update -qq

RUN apt-get install -y build-essential libpq-dev

ENV NODE_ROOT /usr/app/web

RUN mkdir -p $NODE_ROOT

WORKDIR $NODE_ROOT

COPY . .

RUN npm install -g @angular/cli@6
RUN yarn install

EXPOSE 4200

ENTRYPOINT  ["sleep", "2d"]
