FROM        node:10

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN         apt-get update
RUN         npm install @angular/cli@6 
RUN         ng new web --directory ./

RUN         echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc

EXPOSE      3000

RUN         mkdir -p /shk-pilot/web
WORKDIR     /shk-pilot/web

ENTRYPOINT  ["sleep", "2d"]